/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamiliesIndexRouteImport } from './routes/families.index'
import { Route as FamiliesFamilyIdMembersRouteImport } from './routes/families.$familyId.members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesFamilyIdMembersRoute = FamiliesFamilyIdMembersRouteImport.update({
  id: '/families/$familyId/members',
  path: '/families/$familyId/members',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/families/$familyId/members': typeof FamiliesFamilyIdMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/families': typeof FamiliesIndexRoute
  '/families/$familyId/members': typeof FamiliesFamilyIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/families/$familyId/members': typeof FamiliesFamilyIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/families/' | '/families/$familyId/members'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/families' | '/families/$familyId/members'
  id: '__root__' | '/' | '/families/' | '/families/$familyId/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  FamiliesFamilyIdMembersRoute: typeof FamiliesFamilyIdMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$familyId/members': {
      id: '/families/$familyId/members'
      path: '/families/$familyId/members'
      fullPath: '/families/$familyId/members'
      preLoaderRoute: typeof FamiliesFamilyIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  FamiliesFamilyIdMembersRoute: FamiliesFamilyIdMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
